### ISSUE TITLE
'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by nansou520** [ajdgg/nonebot-plugin-xjie-weather#2]
嗯还是我,终于有时间来搞这个了,你给的我放进去了,还是报错但是报错内容不一样了
![QQ截图20240802010433](https://github.com/user-attachments/assets/c1f855ba-01b3-45e2-a7a4-76eebcc6e72a)

**Comment by ajdgg** [comment]
这个报错估计是应该是因为网络问题导致上面函数返回定义报错数组，但在目前我发布的最新版本1.1.13中我没有在主请求函数中抛出这个错误而是直接把数组直接发送请求了，所以导致这个报错，但这个问题已经在当初就已经排查并修改了，只不过到现在还没发布。我应该会在今天晚一点时间发布新版本💦💦💦

**Comment by nansou520** [comment]
好滴

**Comment by ajdgg** [comment]
已经更新1.1.15理论上上面问题已经得到解决

**Comment by nansou520** [comment]
问题解决了,提一点小细节:
1.输入指令后会连续发送三次请求(不管是nonebot响应还是和风控制台都显示3次)
2./st变成了/setup要标注一下,我弄了好就还以为是电脑出问题了awa
3.前面版本不需要@机器人,现在需要了也要标注一下awa

**Comment by ajdgg** [comment]
第一个三次请求是因为要先获取城市编码然后分别获取实时的天气信息和预报信息所以会请求三次，剩下的我会在后面更新中补上

**Comment by nansou520** [comment]
okk谢谢作者大大

**Comment by ajdgg** [comment]
没事
